Ideas for possible improvements
bradygaster/Contoso.Online.Orders pull request #3
Opened 2021-02-14 10:48 UTC by serpent5

Thanks for this awesome sample and the blog series that goes with it.

After reading through the first blog post and looking at the API project here, I have a few ideas for possible improvements that I'd like to share. I'll review my own changes to describe my thinking behind the changes. I understand that this is just meant as a sample project, so feel free to dismiss anything/everything accordingly.

I have a few more ideas around exception-handling here, but I'll save that for another time, if appropriate.

2021-02-14 10:59 UTC, serpent5 reviewed
I really hope this is helpful.

Feel free to close the PR and apply a subset of the ideas yourself, or to just close this out as too over-the-top. :)

2021-02-14 10:59 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +            StoreServices.GetOrders();
All of the actions in the two controllers use `async`, but none of them actually need to be `async`. I've made changes here to clean up the noise of `async`, but another option would be to make the `IStoreServices` methods async. The implementation of those would end up using `Task.FromResult` and such, but it might make for more of a representative sample controller.

I also changed from `ActionResult<T>` to just `T`, because the action only ever returns `T`.

2021-02-14 10:59 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +        public ActionResult<Order> GetOrder(Guid id)
`[FromRoute]` isn't needed here, but I understand that it might be viewed as being more expressive, though.

2021-02-14 10:59 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +            return order;
Because the action already uses `ActionResult<T>`, we can return `T` here instead of wrapping it in `Ok(T)`. This change shows off that benefit.

2021-02-14 10:59 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +                    return NotFound();
I find returning directly like this much easier to follow in these examples, but I'm aware that might be subjective.

2021-02-14 10:59 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +        public IActionResult UpdateProductInventory(int id, InventoryUpdateRequest request)
`[FromBody]` can also be removed from this one, as it's inferred.

2021-02-14 10:59 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> -    [Route("[controller]")]
All of the actions have explicit route templates, so this wasn't used.

2021-02-14 10:59 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/ShopController.cs
> +        [HttpGet("/products/page/{pageNumber}", Name = nameof(GetProductsPage))]
Using `page` as a route value can cause issues in ASP.NET Core. It works fine in this example, but the docs advises against using it [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-5.0#reserved-routing-names).

2021-02-16 07:38 UTC, bradygaster commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +            StoreServices.GetOrders();
I'd prefer keep the API methods async. Say the first "real" implementation of `IStoreService` uses a DB, or a data-store that would require async calls via HTTP? I feel like leaving the Web API methods async gives us that room to grow. 

Do you feel the async-ness adds that much noise to the demo? If so I can understand wanting to remove it all, but I'd prefer "do async right" than "not do async," so I'm open to discuss it more.

2021-02-16 07:39 UTC, bradygaster commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +        public ActionResult<Order> GetOrder(Guid id)
I like crisp. :) Maybe too much so. :) This one I can support. 👍

2021-02-16 07:44 UTC, bradygaster commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +            return order;
But when you do that you lose the crisp HTTP semantics in the method. We want to return the `Ok` or the `NotFound`, not the model on its own. If returning a model on its own explicitly results with an `Ok` response for a GET, I'd be a little more comfortable with this approach, but only if the GET returns a 200, the POST a created, and so on. I don't know if we're **that** adherent to the HTTP spec with the response codes. Also, the article shows how to use the Web API Analyzer, and I think that relies on the return types being `ActionResult<T>` inheritors. 

Since I am in doubt here, i'd prefer be OCD on this one, and be explicit about the return types being `ActionResult`s.

2021-02-16 07:46 UTC, bradygaster commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +        public IActionResult UpdateProductInventory(int id, InventoryUpdateRequest request)
True. I think you see that I error on the side of telling it what I want it to do explicitly.

2021-02-16 07:46 UTC, bradygaster commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +        public IActionResult UpdateProductInventory(int id, InventoryUpdateRequest request)
That said, if there's a perf reason, or a bloat reason, or something-other-than-stylistic-variance, I'm receptive to learning.

2021-02-16 07:47 UTC, bradygaster commented on ContosoOnlineOrders.Api/Controllers/ShopController.cs
> +        [HttpGet("/products/page/{pageNumber}", Name = nameof(GetProductsPage))]
AYE. This is good!

2021-02-16 07:49 UTC, bradygaster requested changes
I think some of these are stylistic things. I'd prefer we take some of these out. I do like a lot of your suggestions, though. Can we remove the async tweak OR move that into the `IStoreService` and thus, leave the async in place? 

I'm also okay with removing the `FromRoute` and `FromBody` - those are good picks. Those could be considered me being OCD. :) 

Thanks for taking an interest in the demo code! If you're doing a lot of Web API and have some ideas, let's try to find a way to sync up. I'd love to hear more from you on what we can do better.

2021-02-16 10:03 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +            StoreServices.GetOrders();
I think there's a fair bit of noise: the `async Task<ActionResult<...>>` wrapper around the return type. It means there's a lot of `async Task<..>` and `await Task.FromResult` in the sample that doesn't get used. I think making the `IStoreServices` methods async would be better overall, but I didn't want to mess with anything outside the controllers.

2021-02-16 10:06 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +            return order;
I think it works either way. If you return `T` directly, without wrapping it in `Ok`, you still get a `200` response. If you want something else, like the `201`, then you need the `Created` wrapper, etc.

I'm probably missing something, but that's how I understand it. Again, it doesn't hurt to be explicit, if that's what you prefer. I'm not aware of the analysers treating things differently here, but I'm not an expert.

2021-02-16 10:07 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +                    return NotFound();
Yeah, sorry about this. I think I forgot to change my default logging level from verbose. 🤭

2021-02-16 10:08 UTC, serpent5 commented on ContosoOnlineOrders.Api/Controllers/AdminController.cs
> +        public IActionResult UpdateProductInventory(int id, InventoryUpdateRequest request)
No, I don't think there's any reason other than it being implied due to the `[ApiController]` attribute.

2021-02-16 10:15 UTC, serpent5 commented
Thanks for taking the time to review my suggestions. I wasn't expecting this to be something that gets merged, but I thought it would be the easiest way to communicate my ideas. If you have the time and desire, feel free to apply the changes that you do agree with directly and close this PR. I am more than happy to do the work, though.

I do use Web API, but most of this feedback comes from helping with the official docs for ASP.NET Core. I don't think I'm going to be a good source for how the framework could do things differently, though.

2021-02-22 10:56 UTC, closed without merging